/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import dao.CidadeDAO;
import dao.ClienteDAO;
import dao.ClienteFisicoDAO;
import dao.ClienteJuridicoDAO;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.ObjCidade;
import model.ObjCliente;
import model.ObjClienteFisico;
import model.ObjClienteJuridico;

/**
 *
 * @author assparremberger
 */
public class FrmCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmCliente
     */
    private boolean novo;
    private Object cliente;
    private List<ObjCidade> listaDeCidades;
    private ListClientes telaListClientes;
    
    public FrmCliente() {
        initComponents();
        esconder();
        carregarCidades();
        lblCodigo.setText("");
        novo = true;
    }
    
    public FrmCliente(int codigo, ListClientes telaListClientes) {
        initComponents();
        esconder();
        carregarCidades();
        novo = false;
        cliente = ClienteDAO.getClienteByCodigo(codigo);
        carregarFormulario();
        this.telaListClientes = telaListClientes;
    }
    
    private void carregarFormulario(){
        ObjCliente cli = (ObjCliente) cliente;
        txtNome.setText( cli.getNome() );
        txtTelefone.setText( cli.getTelefone() );
        txtEndereco.setText( cli.getEndereco());
        lblCodigo.setText( String.valueOf( cli.getCodigo() ) );
        
        for (int i = 1; i < listaDeCidades.size() ; i++) {
            ObjCidade cid = listaDeCidades.get( i );
            if( cid.getCodigo() == cli.getCidade().getCodigo() ){
                cmbCidade.setSelectedIndex( i );
                break;
            }
        }
        
        if( cli.getTipo().equals(  ObjCliente.PESSOA_FISICA ) ){
            ObjClienteFisico cf = (ObjClienteFisico) cliente;
            rbPF.setSelected( true );
            txtCPF.setText( cf.getCpf() );
            txtRG.setText( cf.getRg());
        }
        
        if( cli.getTipo().equals(  ObjCliente.PESSOA_JURIDICA ) ){
            ObjClienteJuridico cj = (ObjClienteJuridico) cliente;
            rbPJ.setSelected( true );
            txtCNPJ.setText( cj.getCnpj());
            txtIE.setText( cj.getIe());
        }
        
    }
    
    private void carregarCidades(){
        listaDeCidades =  CidadeDAO.getCidades();
        ObjCidade fake = new ObjCidade( 0, "Selecione...");
        listaDeCidades.add( 0 , fake);
        
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        
        for( ObjCidade cid : listaDeCidades){
            modelo.addElement( cid );
        }
        cmbCidade.setModel( modelo );
        
    }

    private void esconder(){
        lblCPF.setVisible( false );
        txtCPF.setVisible( false );
        lblRG.setVisible( false );
        txtRG.setVisible( false );
        lblCNPJ.setVisible( false );
        txtCNPJ.setVisible( false );
        lblIE.setVisible( false );
        txtIE.setVisible( false );
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipo = new javax.swing.ButtonGroup();
        lblCodigo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbCidade = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        rbPF = new javax.swing.JRadioButton();
        rbPJ = new javax.swing.JRadioButton();
        lblCPF = new javax.swing.JLabel();
        txtCPF = new javax.swing.JFormattedTextField();
        lblRG = new javax.swing.JLabel();
        txtRG = new javax.swing.JTextField();
        lblCNPJ = new javax.swing.JLabel();
        txtCNPJ = new javax.swing.JFormattedTextField();
        lblIE = new javax.swing.JLabel();
        txtIE = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Formulário de Cliente");

        lblCodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCodigo.setText("000");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Código: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Nome: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Telefone:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Endereço:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Cidade: ");

        cmbCidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbCidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Alvorada", "Canoas", "Capão da Canoa", "Porto Alegre", "Tangamandápio" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Tipo:");

        buttonGroupTipo.add(rbPF);
        rbPF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbPF.setText("Pessoa Física");
        rbPF.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbPFItemStateChanged(evt);
            }
        });
        rbPF.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbPFStateChanged(evt);
            }
        });
        rbPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPFActionPerformed(evt);
            }
        });

        buttonGroupTipo.add(rbPJ);
        rbPJ.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbPJ.setText("Pessoa Jurídica");
        rbPJ.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbPJItemStateChanged(evt);
            }
        });

        lblCPF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCPF.setText("CPF:");

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblRG.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRG.setText("RG:");

        lblCNPJ.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCNPJ.setText("CNPJ:");

        try {
            txtCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblIE.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblIE.setText("IE:");

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCPF)
                                .addGap(26, 26, 26)
                                .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblRG)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(rbPF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbPJ))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtEndereco))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtTelefone))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCNPJ)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblIE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtIE, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(127, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(rbPF)
                    .addComponent(rbPJ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCPF)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblRG)
                        .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCNPJ)
                        .addComponent(txtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblIE)
                        .addComponent(txtIE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPFActionPerformed
       
    }//GEN-LAST:event_rbPFActionPerformed

    private void rbPFStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbPFStateChanged
        
    }//GEN-LAST:event_rbPFStateChanged

    private void rbPFItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbPFItemStateChanged
        if( rbPF.isSelected() ){
            escolherPF();
        }else{
            escolherPJ();
        }
    }//GEN-LAST:event_rbPFItemStateChanged

    private void rbPJItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbPJItemStateChanged
        if( rbPJ.isSelected() ){
            escolherPJ();
        }else{
            escolherPF();
        }
    }//GEN-LAST:event_rbPJItemStateChanged

    private void limparFormulario(){
        txtNome.setText("");
        txtTelefone.setText("");
        txtEndereco.setText("");
        txtCPF.setText("");
        txtCNPJ.setText("");
        txtRG.setText("");
        txtIE.setText("");
        buttonGroupTipo.clearSelection();
        cmbCidade.setSelectedIndex(0);
        esconder();
    }
    
    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparFormulario();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        String nome = txtNome.getText();
        ObjCidade cidade = (ObjCidade) cmbCidade.getSelectedItem();
        if( nome.isEmpty() || cidade.getCodigo() == 0 ){
            JOptionPane.showMessageDialog(this, 
                    "Preencha todos os campos obrigatórios! (Nome e Cidade)");
        }else{
            if( rbPF.isSelected() ){
                ObjClienteFisico cf = new ObjClienteFisico();
                cf.setNome( nome );
                cf.setEndereco( txtEndereco.getText() );
                cf.setTelefone( txtTelefone.getText() );
                cf.setCidade( cidade );
                cf.setTipo( ObjCliente.PESSOA_FISICA );
                cf.setCpf( txtCPF.getText() );
                cf.setRg( txtRG.getText() );
                
                if( novo ){
                    ClienteFisicoDAO.inserir( cf );
                }else{
                    cf.setCodigo( Integer.valueOf( lblCodigo.getText() ) );
                    ClienteFisicoDAO.editar( cf );
                    telaListClientes.carregarTabela( ObjCliente.PESSOA_FISICA);
                }
            }else if ( rbPJ.isSelected() ) {
                ObjClienteJuridico cj = new ObjClienteJuridico();
                cj.setNome( nome );
                cj.setEndereco( txtEndereco.getText() );
                cj.setTelefone(txtTelefone.getText() );
                cj.setCnpj( txtCNPJ.getText() );
                cj.setIe( txtIE.getText() );
                cj.setCidade( cidade );
                cj.setTipo( ObjCliente.PESSOA_JURIDICA );
                if(novo){
                    ClienteJuridicoDAO.inserir( cj );
                }else{
                    cj.setCodigo( Integer.valueOf( lblCodigo.getText() ) );
                    ClienteJuridicoDAO.editar( cj );
                    telaListClientes.carregarTabela( ObjCliente.PESSOA_JURIDICA);
                }
                
            }else{
                ObjCliente cli = new ObjCliente();
                cli.setNome( nome );
                cli.setTelefone( txtTelefone.getText() );
                cli.setEndereco( txtEndereco.getText() );
                cli.setTipo("");
                cli.setCidade( cidade );
                if( novo ){
                    ClienteDAO.inserir( cli );
                }else{
                    cli.setCodigo( Integer.valueOf( lblCodigo.getText() ) );
                    ClienteDAO.editar( cli );
                    telaListClientes.carregarTabela( "" );
                }
            }
            limparFormulario();
            if( !novo ){
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed
    private void escolherPF(){
        lblCPF.setVisible( true );
        lblRG.setVisible( true );
        txtCPF.setVisible( true );
        txtRG.setVisible( true );
        lblCNPJ.setVisible( false );
        lblIE.setVisible( false );
        txtCNPJ.setVisible( false );
        txtIE.setVisible( false );
    }
    private void escolherPJ(){
        lblCPF.setVisible( false );
        lblRG.setVisible( false );
        txtCPF.setVisible( false );
        txtRG.setVisible( false );
        lblCNPJ.setVisible( true );
        lblIE.setVisible( true );
        txtCNPJ.setVisible( true );
        txtIE.setVisible( true );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroupTipo;
    private javax.swing.JComboBox<String> cmbCidade;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblCNPJ;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblIE;
    private javax.swing.JLabel lblRG;
    private javax.swing.JRadioButton rbPF;
    private javax.swing.JRadioButton rbPJ;
    private javax.swing.JFormattedTextField txtCNPJ;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtIE;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRG;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
